### ISSUE TITLE
mailto button behaviour

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#15]
Use https://mailtoui.com/#custom-css

- [ ] Use dark colours based on the current design. We can tweak together at the end.
- [ ] Get rid of all the elements in red via the options or via CSS:
<img width="534" alt="Screenshot 2020-12-12 at 13 58 21" src="https://user-images.githubusercontent.com/3253920/101975812-cac11a80-3c82-11eb-8c05-13e41449902e.png">

- [ ] The end result should look something similar to this:

<img width="534" alt="mailto popup" src="https://user-images.githubusercontent.com/3253920/101975880-576bd880-3c83-11eb-9def-dc944c567881.png">

**Comment by fergusmeiklejohn** [comment]
I'm having trouble getting this to work with the button. I've opened an issue on the repo, lets wait a few days and see

**Comment by mesqueeb** [comment]
@fergusmeiklejohn if there's no function to launch the modal on button click you can just use the `a` tag as per their docs:
`<a class="mailtoui" href="mailto:tony.stark@example.com">Contact Tony</a>`
and make that look like the button. You could make some tweaks to the button vue file to support both `button` and `a` tags, make them use the same CSS and add some v-ifs in the template! shouldn't be too hard.
