### ISSUE TITLE
try increased padding in framework card

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#22]
Making my desired changes in the browser for the sake of being able to take a screenshot showed me that the underlying code can improve a lot.

the main reason is, I had to make _a lot of changes to achieve my desired result_.
that means that the code is written in a way that is a bit too difficult to easily update.

**this is an area I can give a lot of advice on, so let's go over it together!**

current:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/3253920/104082484-e1569380-5279-11eb-87b7-1ee47c1818ef.png">

desired:
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/3253920/104082557-7d809a80-527a-11eb-950b-030445cf82ba.png">

**Comment by mesqueeb** [comment]
@fergusmeiklejohn 

so for this issue:

- [x] extract the actual "card" as  FrameworkCard.vue
- [x] make the discussed "increased padding" CSS optimisations in that new component
- [x] then, also see related issue: https://github.com/CyCraft/cycraft.co/issues/28

**Comment by fergusmeiklejohn** [comment]
padding not working against an absolute positioned element
