### ISSUE TITLE
more margin around social links & no uppercase

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#25]
- [x] social links are not uppercase on design. before you fix this, **double check if this is a fix that should be made at the typography level for the entire typography class or is just specific to these social links**

- [x] We can use a bit more space around the social icons as per screenshot down below.

- [x] Make sure if they're stacked vertically on mobile there's also enough space in between them.

currently: 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/3253920/104082689-6f7f4980-527b-11eb-8998-b8695e9552f5.png">

and on mobile currently:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/3253920/104082886-43fd5e80-527d-11eb-854e-ae8305bced54.png">

design:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3253920/104082679-655d4b00-527b-11eb-8288-913983e3f2ff.png">

**Comment by fergusmeiklejohn** [comment]
#1 font class changed to h4
#2 added for +1024px screen sizes to prevent vertical stacking on smaller screens which looks bad
#3 breakpoint padding and margin changed to prevent vertical stacking
