### ISSUE TITLE
make framework cards clickable and open project in same page

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#28]
- [x] extract the actual "card" as FrameworkCard.vue
 
- [x] these cards should be clickable and open the project in same page:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/3253920/104082758-03e9ac00-527c-11eb-9baa-289cedc5ae85.png">

the best implementation (for accessibility reasons) is use an anchor tag without any styling that wraps the framework card

- [ ] when hovering anywhere over the card, the actual link inside the card should show an underline (like a regular anchor tag would show at all times) (try to implement this with purely CSS)

**Comment by fergusmeiklejohn** [comment]
I've having a bit of trouble with this one. Spent far too much time on it (which I won't count) but I'm stuck.
I've completed extracting FrameworkCard into its own component.
Problem 1: card is remade with position: absolute, but now you can't add margin between the text and the svg
Problem 2: I've got the textUrl below the title to animate underline on hover (like a regular anchor tag) but I can't get hover on the parent to pass down to the child.
Problem 3: This extraction process has made the animation not work well. If you click quickly between the three frameworks you'll see the card appear below the site then vanish and animate in.
