### ISSUE TITLE
fix project links on mobile

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#30]
on mobile size on hover nothing shows up:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/3253920/104082829-a99d1b00-527c-11eb-85d2-dee537d98d88.png">

Fix this to be:

- [x] clicking the project card once the external link shows up like it does on hover on desktop.
- [ ] clicking it a second time will open the project URL in the same page.
- [x] hover behaviour doesn't matter on mobile size, can be kept the same as desktop

**Comment by fergusmeiklejohn** [comment]
As a user I don't like to open external links in the same page. This site forces users to watch a loading animation for 5 secs every time they visit the page, so clicking on a project will navigate to that project site in the same page then clicking back will load the animation again and lose the scroll position. It's not good UX I'd argue.

**Comment by fergusmeiklejohn** [comment]
I've marked this as done pending review, but links are still to an external page. If you still want links on same page just say and I'll make that change :-)
