### ISSUE TITLE
should not have horizontal scroll on mobile

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/cycraft.co#34]
there seems to be a horizontal scroll on mobile... 🤔

<img width="346" alt="Screenshot 2021-01-09 at 13 22 45" src="https://user-images.githubusercontent.com/3253920/104082969-e87fa080-527d-11eb-81c6-8b553df98a4d.png">

(this was tested with iPhone 5/SE)
<img width="295" alt="image" src="https://user-images.githubusercontent.com/3253920/104082989-0a792300-527e-11eb-9ad1-0f0587431eb7.png">

**Comment by fergusmeiklejohn** [comment]
I can't reproduce this.
I've already added this css to App.vue to stop over scrolling
```
body
  height: 100vh
  background-color: black
  overscroll-behavior-y: none
  overscroll-behavior-x: none
```
